# Generated by Django 4.2.23 on 2025-06-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the image', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Title of the blog post', max_length=100)),
                ('content', models.CharField(help_text='Contents of the blog post', max_length=255)),
            ],
        ),
    ]
